#!/usr/bin/env bash
# setup-repo-env.sh — bootstrap per-repo AI CLI isolation
#
# Usage:
#   setup-repo-env.sh [--op] [repo-path]
#
# --op   Write a 1Password .envrc (no local .env needed) instead of dotenv-based one
#
# What it does:
#   1. Creates an isolated CODEX_HOME at ~/.codex-repos/<repo-name>/
#   2. Writes config.toml routing Codex to the gateway with auto-approve
#   3. Writes a .envrc into the repo root
#   4. Runs `direnv allow` to whitelist it

set -euo pipefail

GATEWAY_URL="${GATEWAY_URL:-http://localhost:4000}"
OP_VAULT="ai-gateway"
OP_ITEM="dev-secrets"

use_op=0
repo_path=""

for arg in "$@"; do
    case "$arg" in
        --op) use_op=1 ;;
        *)    repo_path="$arg" ;;
    esac
done

# Resolve repo root
if [[ -z "$repo_path" ]]; then
    repo_path=$(git rev-parse --show-toplevel 2>/dev/null || echo "$PWD")
fi
repo_path=$(realpath "$repo_path")
repo_name=$(basename "$repo_path")
codex_home="$HOME/.codex-repos/$repo_name"

echo "→ Repo:       $repo_path"
echo "→ CODEX_HOME: $codex_home"

# 1. Create isolated CODEX_HOME
mkdir -p "$codex_home"

# 2. Write config.toml (remove any stale auth.json so Codex uses OPENAI_API_KEY env var)
rm -f "$codex_home/auth.json"
cat > "$codex_home/config.toml" <<TOML
# Auto-generated by setup-repo-env.sh — safe to re-run
openai_base_url = "${GATEWAY_URL}/v1"
approval_policy = "never"
model = "gpt-4o"

[projects."${repo_path}"]
trust_level = "trusted"
TOML
echo "→ Wrote $codex_home/config.toml"

# 3. Write .envrc
envrc_path="$repo_path/.envrc"
has_env=$([[ -f "$repo_path/.env" ]] && echo 1 || echo 0)

if [[ $use_op -eq 1 ]] || [[ $has_env -eq 0 ]]; then
    # 1Password variant — no .env needed
    cat > "$envrc_path" <<ENVRC
export CODEX_HOME="\$HOME/.codex-repos/${repo_name}"

# Load API keys from 1Password vault (requires ~/.op-token with OP_SERVICE_ACCOUNT_TOKEN)
export OPENAI_API_KEY=\$(op read "op://${OP_VAULT}/${OP_ITEM}/OPENAI_API_KEY" 2>/dev/null)
export ANTHROPIC_API_KEY=\$(op read "op://${OP_VAULT}/${OP_ITEM}/ANTHROPIC_API_KEY" 2>/dev/null)
export GEMINI_API_KEY=\$(op read "op://${OP_VAULT}/${OP_ITEM}/GEMINI_API_KEY" 2>/dev/null)
export ANTIGRAVITY_API_KEY=\$(op read "op://${OP_VAULT}/${OP_ITEM}/ANTIGRAVITY_API_KEY" 2>/dev/null)
export CURSOR_API_KEY=\$(op read "op://${OP_VAULT}/${OP_ITEM}/CURSOR_API_KEY" 2>/dev/null)

export ANTHROPIC_BASE_URL=${GATEWAY_URL}
export GOOGLE_GEMINI_BASE_URL=${GATEWAY_URL}
export OPENAI_BASE_URL=${GATEWAY_URL}/v1
export ANTIGRAVITY_API_BASE=${GATEWAY_URL}/v1
export CURSOR_API_BASE=${GATEWAY_URL}/v1
ENVRC
    echo "→ Wrote .envrc (1Password variant)"
else
    # dotenv variant — loads from local .env, overrides CODEX_HOME
    cat > "$envrc_path" <<ENVRC
dotenv
export CODEX_HOME="\$HOME/.codex-repos/${repo_name}"
ENVRC
    echo "→ Wrote .envrc (dotenv variant)"
fi

# 4. direnv allow
if command -v direnv &>/dev/null; then
    direnv allow "$repo_path"
    echo "→ direnv allowed"
else
    echo "⚠ direnv not found — install it and run: direnv allow $repo_path"
fi

# 5. Remind about .gitignore
if [[ -f "$repo_path/.gitignore" ]]; then
    if ! grep -q '\.envrc' "$repo_path/.gitignore"; then
        echo ""
        echo "⚠ Add .envrc to $repo_path/.gitignore (it may contain secrets via 1Password)"
        echo "  echo '.envrc' >> $repo_path/.gitignore"
    fi
fi

echo ""
echo "Done. cd into $repo_path and API keys + CODEX_HOME load automatically."
