#!/bin/sh
# Render litellm-config.yaml into a Kubernetes ConfigMap for the ai-gateway-staging
# namespace and print it to stdout. The embedded YAML is validated before emission so a
# malformed config never lands in the GitOps overlay.
#
# Usage:
#   scripts/ops/generate-staging-configmap.sh > overlays/staging/litellm-config.configmap.yaml
#
# Overridable via environment (defaults target the staging overlay):
#   LITELLM_CONFIG   path to the source config     (default: <repo>/litellm-config.yaml)
#   STAGING_NAMESPACE  target namespace            (default: ai-gateway-staging)
#   CONFIGMAP_NAME     ConfigMap metadata.name     (default: litellm-config)
#
# POSIX sh + python3 (stdlib yaml) only — no extra dependencies.
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "${SCRIPT_DIR}/.." && pwd)

CONFIG_FILE="${LITELLM_CONFIG:-${REPO_ROOT}/litellm-config.yaml}"
NAMESPACE="${STAGING_NAMESPACE:-ai-gateway-staging}"
CONFIGMAP_NAME="${CONFIGMAP_NAME:-litellm-config}"

if ! command -v python3 >/dev/null 2>&1; then
    echo "error: python3 is required for YAML validation" >&2
    exit 1
fi

if [ ! -f "${CONFIG_FILE}" ]; then
    echo "error: litellm config not found: ${CONFIG_FILE}" >&2
    exit 1
fi

CONFIG_FILE="${CONFIG_FILE}" NAMESPACE="${NAMESPACE}" CONFIGMAP_NAME="${CONFIGMAP_NAME}" \
python3 - <<'PY'
import os
import sys

try:
    import yaml
except ModuleNotFoundError:
    sys.stderr.write("error: python3 'yaml' module (PyYAML) is required\n")
    sys.exit(1)

path = os.environ["CONFIG_FILE"]
namespace = os.environ["NAMESPACE"]
name = os.environ["CONFIGMAP_NAME"]

with open(path, "r", encoding="utf-8") as fh:
    raw = fh.read()

# Fail loudly if the source config is not parseable YAML — the ConfigMap must never
# ship a broken litellm-config to the cluster.
try:
    parsed = yaml.safe_load(raw)
except yaml.YAMLError as exc:
    sys.stderr.write(f"error: {path} is not valid YAML: {exc}\n")
    sys.exit(1)

if not isinstance(parsed, dict) or "model_list" not in parsed:
    sys.stderr.write(
        f"error: {path} does not look like a litellm config (missing top-level 'model_list')\n"
    )
    sys.exit(1)


def indent_block(text, prefix="    "):
    lines = []
    for line in text.splitlines():
        # Keep blank lines truly empty; YAML literal blocks preserve them as newlines.
        lines.append(prefix + line if line.strip() else "")
    return "\n".join(lines)


header = f"""# Generated by scripts/ops/generate-staging-configmap.sh — do not edit by hand.
# Source of truth: litellm-config.yaml (rendered for the staging overlay).
apiVersion: v1
kind: ConfigMap
metadata:
  name: {name}
  namespace: {namespace}
  labels:
    app.kubernetes.io/name: ai-gateway
    app.kubernetes.io/component: litellm
    app.kubernetes.io/part-of: ai-gateway
    app.kubernetes.io/instance: ai-gateway-staging
    app.kubernetes.io/managed-by: argocd
data:
  litellm-config.yaml: |
"""

out = header + indent_block(raw) + "\n"
sys.stdout.write(out)

# Re-parse the block scalar we just emitted to guarantee the embedded YAML round-trips.
manifest = yaml.safe_load(out)
embedded = manifest["data"]["litellm-config.yaml"]
try:
    yaml.safe_load(embedded)
except yaml.YAMLError as exc:
    sys.stderr.write(f"error: embedded ConfigMap YAML failed to re-parse: {exc}\n")
    sys.exit(1)
PY
