#!/usr/bin/env bash
# setup-repo-env.sh — bootstrap per-repo AI CLI isolation
#
# Usage:
#   setup-repo-env.sh [--op] [--org ORG] [--workspace WS] [--team TEAM] [--env ENV] [repo-path]
#
# --op          Write a 1Password .envrc (no local .env needed) instead of dotenv-based one
# --org         Tenant org slug (default: echoares)
# --workspace   Workspace slug (default: core)
# --team        Team slug (default: eng) — single segment; see docs/TENANCY.md
# --env         Environment slug (default: dev)
#
# What it does:
#   1. Creates an isolated CODEX_HOME at ~/.codex-repos/<repo-name>/
#   2. Writes config.toml routing Codex to the gateway with auto-approve
#   3. Writes a .envrc into the repo root (includes tenant key naming guidance)
#   4. Runs `direnv allow` to whitelist it
#
# Gateway API keys should follow: ak-{org}-{workspace}-{team}-{repo}-{environment}
# so the gateway-engine can attach tenant metadata (docs/TENANCY.md).

set -euo pipefail

GATEWAY_URL="${GATEWAY_URL:-http://localhost:4000}"
OP_VAULT="ai-gateway"
OP_ITEM="dev-secrets"

TENANT_ORG="${TENANT_ORG:-echoares}"
TENANT_WORKSPACE="${TENANT_WORKSPACE:-core}"
TENANT_TEAM="${TENANT_TEAM:-eng}"
TENANT_ENV="${TENANT_ENV:-dev}"

use_op=0
repo_path=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --op) use_op=1; shift ;;
        --org) TENANT_ORG="${2:?--org requires a value}"; shift 2 ;;
        --workspace) TENANT_WORKSPACE="${2:?--workspace requires a value}"; shift 2 ;;
        --team) TENANT_TEAM="${2:?--team requires a value}"; shift 2 ;;
        --env) TENANT_ENV="${2:?--env requires a value}"; shift 2 ;;
        -h | --help)
            sed -n '2,22p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *) repo_path="$1"; shift ;;
    esac
done

# Resolve repo root
if [[ -z "$repo_path" ]]; then
    repo_path=$(git rev-parse --show-toplevel 2>/dev/null || echo "$PWD")
fi
repo_path=$(realpath "$repo_path")
repo_name=$(basename "$repo_path")
codex_home="$HOME/.codex-repos/$repo_name"
tenant_key="ak-${TENANT_ORG}-${TENANT_WORKSPACE}-${TENANT_TEAM}-${repo_name}-${TENANT_ENV}"

echo "→ Repo:         $repo_path"
echo "→ CODEX_HOME:   $codex_home"
echo "→ Tenant key:   $tenant_key  (use as Authorization: Bearer … in LiteLLM)"

# 1. Create isolated CODEX_HOME
mkdir -p "$codex_home"

# 2. Write config.toml (remove any stale auth.json so Codex uses OPENAI_API_KEY env var)
rm -f "$codex_home/auth.json"
cat > "$codex_home/config.toml" <<TOML
# Auto-generated by setup-repo-env.sh — safe to re-run
openai_base_url = "${GATEWAY_URL}/v1"
approval_policy = "never"
model = "gpt-4o"

[projects."${repo_path}"]
trust_level = "trusted"
TOML
echo "→ Wrote $codex_home/config.toml"

# 3. Write .envrc
envrc_path="$repo_path/.envrc"
has_env=$([[ -f "$repo_path/.env" ]] && echo 1 || echo 0)

_tenant_block() {
    cat <<ENVRC
# Tenancy (epic #30 — docs/TENANCY.md)
export GATEWAY_TENANT_ORG="${TENANT_ORG}"
export GATEWAY_TENANT_WORKSPACE="${TENANT_WORKSPACE}"
export GATEWAY_TENANT_TEAM="${TENANT_TEAM}"
export GATEWAY_TENANT_ENV="${TENANT_ENV}"
export GATEWAY_TENANT_KEY_LABEL="${tenant_key}"
# LiteLLM virtual key should match this label; map to client env vars below.
ENVRC
}

if [[ $use_op -eq 1 ]] || [[ $has_env -eq 0 ]]; then
    # 1Password variant — no .env needed
    {
        _tenant_block
        cat <<ENVRC
export CODEX_HOME="\$HOME/.codex-repos/${repo_name}"

# Load API keys from 1Password vault (requires ~/.op-token with OP_SERVICE_ACCOUNT_TOKEN)
export OPENAI_API_KEY=\$(op read "op://${OP_VAULT}/${OP_ITEM}/OPENAI_API_KEY" 2>/dev/null)
export ANTHROPIC_API_KEY=\$(op read "op://${OP_VAULT}/${OP_ITEM}/ANTHROPIC_API_KEY" 2>/dev/null)
export GEMINI_API_KEY=\$(op read "op://${OP_VAULT}/${OP_ITEM}/GEMINI_API_KEY" 2>/dev/null)
export ANTIGRAVITY_API_KEY=\$(op read "op://${OP_VAULT}/${OP_ITEM}/ANTIGRAVITY_API_KEY" 2>/dev/null)
export CURSOR_API_KEY=\$(op read "op://${OP_VAULT}/${OP_ITEM}/CURSOR_API_KEY" 2>/dev/null)

export ANTHROPIC_BASE_URL=${GATEWAY_URL}
export GOOGLE_GEMINI_BASE_URL=${GATEWAY_URL}
export OPENAI_BASE_URL=${GATEWAY_URL}/v1
export ANTIGRAVITY_API_BASE=${GATEWAY_URL}/v1
export CURSOR_API_BASE=${GATEWAY_URL}/v1
ENVRC
    } > "$envrc_path"
    echo "→ Wrote .envrc (1Password variant)"
else
    # dotenv variant — loads from local .env, overrides CODEX_HOME
    {
        _tenant_block
        cat <<ENVRC
dotenv
export CODEX_HOME="\$HOME/.codex-repos/${repo_name}"

# Allow overriding the gateway URL dynamically for dev slot testing
GATEWAY_URL="\${GATEWAY_URL:-${GATEWAY_URL}}"
export ANTHROPIC_BASE_URL="\${GATEWAY_URL}"
export GOOGLE_GEMINI_BASE_URL="\${GATEWAY_URL}"
export OPENAI_BASE_URL="\${GATEWAY_URL}/v1"
export ANTIGRAVITY_API_BASE="\${GATEWAY_URL}/v1"
export CURSOR_API_BASE="\${GATEWAY_URL}/v1"
ENVRC
    } > "$envrc_path"
    echo "→ Wrote .envrc (dotenv variant)"
fi

# 4. direnv allow
if command -v direnv &>/dev/null; then
    direnv allow "$repo_path"
    echo "→ direnv allowed"
else
    echo "⚠ direnv not found — install it and run: direnv allow $repo_path"
fi

# 5. Remind about .gitignore
if [[ -f "$repo_path/.gitignore" ]]; then
    if ! grep -q '\.envrc' "$repo_path/.gitignore"; then
        echo ""
        echo "⚠ Add .envrc to $repo_path/.gitignore (it may contain secrets via 1Password)"
        echo "  echo '.envrc' >> $repo_path/.gitignore"
    fi
fi

echo ""
echo "Done. cd into $repo_path and API keys + CODEX_HOME load automatically."
echo "Provision a LiteLLM key labeled ${tenant_key} and set OPENAI_API_KEY / ANTHROPIC_API_KEY to its value."
