name: Auto Approve
on: pull_request_target
permissions:
  pull-requests: write
jobs:
  approve:
    runs-on: ubuntu-latest
    if: github.actor == 'TheNorthWestPassage'
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          review-message: "Auto-approved by orchestrator workflow."
